spring:
  datasource:
    url: jdbc:mysql://39.108.179.140:3306/eblog?useUnicode=true&useSSL=false&characterEncoding=utf8&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  freemarker:
    settings:
      datetime_format: yyyy-mm-dd HH:mm
      number_format: 0.##

  redis:
    host: 39.108.179.140
    port: 6379
    password: 123456
  rabbitmq:
    username: rbRoot
    password: 123123
    host: 39.108.179.140
    port: 5672






mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
qiniu:
  accessKey: qKzAZ3Fhkk79U-0FyzIDMfmgFcdGRgSDn3uNhsuS
  secretKey: JgKhZWmo0lgiBDcW-yprfnZbk5_zjfUQqQStFjde
  bucketName: careyddddd
  fileDomain: qczbhuiem.bkt.clouddn.com
